version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/**'
    base-directory: base_location
    name: dev-backend-build-artifact
    discard-paths: no